import Head from 'next/head'
import Image from 'next/image'
import LoginModal from '../components/LoginModal'
import Layout from "../components/layout";
import {Button, Loading} from "@nextui-org/react"
import { useEffect } from 'react';
import { hasCookie } from 'cookies-next';
import { useRouter } from 'next/router'

export default function Home() {
    return (
        <>
            <Head>
                <title>Looped</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Button disabled auto bordered color="warning" css={{ px: "$13" }}>
                <Loading type="points-opacity" color="currentColor" size="sm" />
            </Button>
        </>
    )
}

export async function getServerSideProps({req, res, query}) {
    //
    // Get search params from url
    //
    

    if (hasCookie("sl-token", {req, res})) {
        return {
            redirect: {
                destination: `${query.path ? query.path : '/'}`,
                permanent: false,
            },
        }
    }
    return {
        props: {}
    }
}
