import Head from 'next/head'
import Image from 'next/image'
import LoginModal from '../components/LoginModal'
import Layout from "../components/layout";
import MailView from "../components/mail";

export default function Mail() {
    return (
        <>
            <Head>
                <title>Mail - Looped</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <MailView />

        </>
    )
}
